### ISSUE TITLE
Restore Revision on Entity with Blocks & Nested Repeaters causing unexpected Blocks Rows

### ISSUE THREAD

**Issue by dkc17** [area17/twill#2660]
## Description

When the entity contains blocks, the blocks with repeaters,
the restore revision function will cause many unexpected rows in blocks table.
And these rows will keep forever and now my production site contains several thousands rows causing very slow performance.

### Steps to reproduce

Create a very simple structure to reproduce:
Make a Module eg. Page
Page Has Blocks
 - Simple Block
 -  - (Repeater) Simple Item
 -  -  - Input Description
 -  -  - (Repeater) Button
 - 
![image](https://github.com/user-attachments/assets/0919eff4-c9c8-43bc-81d9-a89c72abbdc2)

Save data like this:
 - Simple Block
 -  - Simple Item Test A
 -  -  - Button Test 1
 -  -  - Button Test 2
 -  -  - Button Test 3
 - Simple Block
 -  - Simple Item Test B
 -  -  - Button Test 4
 -  -  - Button Test 5
 -  -  - Button Test 6
 - Simple Block
 -  - Simple Item Test C
 -  -  - Button Test 7
 -  -  - Button Test 8
 -  -  - Button Test 9

Publish.

Database blocks would look like this:

![image](https://github.com/user-attachments/assets/a104ae05-3ef5-40b1-ab55-d1d234a579a2)
which is good.

And I Edit 3 buttons, change
"Button Test 7" -> "Button Test 7 edited"
"Button Test 8" -> "Button Test 8 edited"
"Button Test 9" -> "Button Test 9 edited"

Update

Database blocks would look like this:

![image](https://github.com/user-attachments/assets/37105aea-be81-4425-8c13-da0c6bb1f42e)
which is also good.

And we do the "restore" action to last revision.

![image](https://github.com/user-attachments/assets/ea9f4569-081c-4e06-9594-a324b2f45712)

### Expected result

Expect result should be no additional rows are added, just normal as previous database screencap.

### Actual result

However, unexpected rows are added:

![image](https://github.com/user-attachments/assets/a3359a2e-715f-47a1-9143-a3c39a8f9dea)

at id (398, 399, 400, 401)

And these rows seem keep forever, and many other rows would produced everytime restore revision.

And these rows should affecting the performance.

### Versions

Twill version:  2.11.0
Laravel version: v9.52.16
PHP version: PHP 8.1.23
Database engine: MySQL 8.0.30

**Comment by dkc17** [comment]
Attach

```
resources/views/admin/blocks/simple.blade.php
resources/views/admin/pages/form.blade.php
resources/views/admin/repeaters/button.blade.php
resources/views/admin/repeaters/simple_item.blade.php
```

[simple-blocks.zip](https://github.com/user-attachments/files/17111432/simple-blocks.zip)

**Comment by zeezo887** [comment]
Hi @deckchan, this issue has been fixed in the latest version of Twill 2. I'd suggest you upgrade twill to 2.13.0.

**Comment by dkc17** [comment]
@zeezo887 

I have just tested with 2.13.0, the issue still exists

![image](https://github.com/user-attachments/assets/76ce9884-e4f4-440a-a09b-148fdc45cd51)

![image](https://github.com/user-attachments/assets/44398257-9597-44e9-8381-3050e3e8cae8)

### Versions

Twill version: 2.13.0

Laravel version: v9.52.16

PHP version: PHP 8.1.23

Database engine: MySQL 8.0.30
